config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :user, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "pools#index"

    resources :pools do
      collection do
        get :pool_graph, to: 'pools#pool_graph'
      end
    end

  resources :snapshots do
    get :snapshot_graph, to: 'snapshots#snapshot_graph'
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/has_snapshot_children.rb
module HasSnapshotChildren
  extend ActiveSupport::Concern
  
  included do

    include ActiveSnapshot
    
    has_snapshot_children do

      instance = self.class.find(id)

      descendants = instance.descendants.includes(:profile)

      {
        descendants: descendants,
        descendants_profiles: descendants.map { |d| d.profile }
      }
    end
  end
end

app/models/employee.rb
class Employee < Pool
  include HasSnapshotChildren
end

app/models/grade.rb
class Grade < ApplicationRecord

  has_many :profiles, dependent: :restrict_with_error

  validates :name, uniqueness: true
  validates :name, :level, presence: true
  
end

app/models/manager.rb
class Manager < Pool
  include HasSnapshotChildren
end

app/models/mentor.rb
class Mentor < Pool
  include HasSnapshotChildren
end

app/models/pool.rb
class Pool < ApplicationRecord

  before_destroy :change_parent_pools

  belongs_to :profile
  belongs_to :pool_container

  has_closure_tree

  validates :type, presence: true

  def to_digraph_label
    "#{profile.first_name} #{profile.last_name}\n (#{profile.grade.name} / #{profile.speciality.name})"
  end

  def change_parent_pools
    pools_for_update = Pool.where(parent_id: profile.pool.id)
    pools_for_update.each {|pool| pool.update(parent_id: profile.pool.parent_id)}
  end

  def self.to_dot_digraph(tree_scope, highlight_id)
    id_to_instance = tree_scope.reduce({}) { |h, pool| h[pool.id] = pool; h }
    output = StringIO.new
    output << "digraph G {\n"
    tree_scope.each do |pool|
      if id_to_instance.key? pool._ct_parent_id
        output << "  \"#{pool._ct_parent_id}\" -> \"#{pool._ct_id}\" [label = #{pool.type}]\n"
      end

      if highlight_id == pool.profile.id  
        output << "  \"#{pool._ct_id}\" [label=\"#{pool.to_digraph_label}\" color=\"green\" fontcolor=\"green\"]\n"
      else
        output << "  \"#{pool._ct_id}\" [label=\"#{pool.to_digraph_label}\"]\n"
      end
    end
    output << "}\n"
    output.string
  end
end

app/models/pool_container.rb
class PoolContainer < ApplicationRecord
    
    has_many :pools
    belongs_to :user

end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :speciality
  belongs_to :grade
  belongs_to :user
  has_one :pool

  validates :first_name, :last_name, :grade_id, :speciality_id, :user_id, presence: true
  accepts_nested_attributes_for :user, :grade, :speciality

  scope :available, -> { where.not(id: Pool.pluck(:profile_id)) }
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/speciality.rb
class Speciality < ApplicationRecord

  has_many :profiles, dependent: :restrict_with_error

  validates :name, length: { maximum: 255 }, uniqueness: true
  validates :name, presence: true

end

app/models/team_lead.rb
class TeamLead < Pool
  include HasSnapshotChildren
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_one :profile
  has_one :pool_container

  def pool_snapshots
    ActiveSnapshot::Snapshot.where(user: self).includes(:user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :authenticate_user!

  include Pundit::Authorization
  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
  private

  def user_not_authorized
    redirect_to root_path, alert: t('controllers.application_controller.user_not_authorized.flash.alert')
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def google_oauth2
  
    auth ||= request.env['omniauth.auth']

    user = User.find_by(email: auth.info.email)
   
    if user.present?
      sign_out_all_scopes
      sign_in_and_redirect user, event: :authentication
    else
      redirect_to new_user_session_path,
      alert: t('devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized.")
    end
  end
end

app/controllers/pools_controller.rb
class PoolsController < BaseController

  def index
    @pools = []
    @pool_root = nil
    @select_parents = []
    @select_children = []

    if current_user.has_role? :manager || current_user.profile.pool.present?
    
      @pools = current_user.pool_container.pools.order(parent_id: :asc).page(params[:page]).per(5)
        
      @pool_root = current_user.pool_container.pools.root
      
      @select_parents = current_user.pool_container.pools.includes(profile:
        [:grade]).decorate.map { |pool| [pool.full_name_and_grade, pool.id] }

      @select_children = Profile.includes(:grade).available.decorate.map do |profile|
        [profile.full_name_and_grade, profile.id]
      end
    end
  end

  def create
    params = pool_params.merge(pool_container_id: current_user.pool_container.id)

    @pool = Pool.new(params)

    authorize @pool, policy_class: PoolPolicy
    if @pool.save
      snapshot_service.create_snapshot(current_user.pool_container)
      redirect_to root_path, notice: t('controllers.pools_controller.create.flash.notice')
    else
      redirect_to root_path, alert: t('controllers.pools_controller.create.flash.alert')
    end
  end

  def destroy
    @pool = Pool.find(params[:id])

    authorize @pool, policy_class: PoolPolicy

    if @pool.parent_id.present?
      @pool.destroy!
      snapshot_service.create_snapshot(current_user.pool_container)
      redirect_to root_path, notice: t('controllers.pools_controller.destroy.flash.notice')
    else
      redirect_to root_path, alert: t('controllers.pools_controller.destroy.flash.alert')
    end
  end

  def pool_graph
    pools = []
    if current_user.has_role? :manager
      pools = current_user.pool_container.pools.includes(:profile)
    else
      pool = current_user.profile.pool
      if pool.present?
        pools = pool.pool_container.pools
      end
    end
    send_file ::GraphGenerator.new.call(pools, current_user.profile.id)
  end

  private

  def pool_params
    params.require(:pool).permit(:id, :type, :profile_id, :parent_id)
  end

  def snapshot_service
    @snaphost_service ||= SnapshotService.new
  end
end

app/controllers/snapshots_controller.rb
class SnapshotsController < BaseController

  def index
    @snapshots = current_user.pool_snapshots.page(params[:page]).per(5)
  end
  
  def show
    @snapshots = current_user.pool_snapshots.page(params[:page]).per(5)
    @snapshot = ActiveSnapshot::Snapshot.find(params[:id])
  end

  def destroy
    snapshot = ActiveSnapshot::Snapshot.find(params[:id])
    if snapshot.destroy
      redirect_to snapshots_path, notice: t('controllers.snapshots_controller.create.flash.notice')
    else
      redirect_to snapshots_path, alert: t('controllers.snapshots_controller.create.flash.alert')
    end
  end

  def snapshot_graph
    snapshot = ActiveSnapshot::Snapshot.find(params[:snapshot_id])
    restore = ::SnapshotRestore.new.call(snapshot)
    send_file ::GraphGenerator.new.call(restore, current_user.profile.id)
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end
  
  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/views/admin/csv/upload_csv.erb
<%= form_for :dump, url: { action: :import_csv }, html: { multipart: true } do |f| %>
  <div style="display: flex; justify-content: center;align-items: center; gap: 2rem;">
    <%= f.file_field :file, accept: ".csv" %>

    <%= f.submit "Import CSV data" %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="flex justify">
    
      <%= button_to root_path, method: :get,  
      class: 'h-10 px-5 m-2 rounded-md border border-transparent 
          bg-green-700 py-2 px-4 text-sm font-medium text-white hover:bg-green-700 focus:outline-none focus:ring-2 
          focus:ring-green-700 focus:ring-offset-2 flex items-center gap-1' do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M18 18.72a9.094 9.094 0 003.741-.479 3 3 0 00-4.682-2.72m.94 3.198l.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0112 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 016 18.719m12 0a5.971 5.971 0 00-.941-3.197m0 0A5.995 5.995 0 0012 12.75a5.995 5.995 0 00-5.058 2.772m0 0a3 3 0 00-4.681 2.72 8.986 8.986 0 003.74.477m.94-3.197a5.971 5.971 0 00-.94 3.197M15 6.75a3 3 0 11-6 0 3 3 0 016 0zm6 3a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0zm-13.5 0a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0z" />
      </svg>
        <p> Main page </p>
      <% end %>

    <% if current_user.has_role? :manager %>
      <%= button_to snapshots_path, method: :get,  
      class: 'h-10 px-5 m-2 rounded-md border border-transparent 
          bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-600 focus:outline-none focus:ring-2 
          focus:ring-indigo-600 focus:ring-offset-2 flex items-center gap-1' do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.042A8.967 8.967 0 006 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 016 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 016-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0018 18a8.967 8.967 0 00-6 2.292m0-14.25v14.25" />
      </svg>
        <p> Pool history </p>
      <% end %>
    <% end %>

    <%= button_to destroy_user_session_path, method: :delete, 
    class: 'h-10 px-5 m-2 rounded-md border border-transparent 
        bg-red-600 py-2 px-4 text-sm font-medium text-white hover:bg-red-600 focus:outline-none focus:ring-2 
        focus:ring-red-600 focus:ring-offset-2 flex items-center gap-1' do %>
        <p> Logout </p>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15m3 0l3-3m0 0l-3-3m3 3H9" />
    </svg>
    <% end %>   
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StepanovWork</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%# <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>

  <% if user_signed_in? %>
    <%= render 'layouts/header' %>
  <% end %>

  <% if notice %>
    <p class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="notice"><%= notice %></p>
  <% end %>

  <% if alert %>
    <p class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert"><%= alert %></p>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/pools/_history_tree.erb
<table class="shadow-lg bg-white border-separate text-left mx-auto">
  <tr>
    <th class="bg-green-200 border text-center px-8 py-4">Id</th> 
    <th class="bg-green-200 border text-center px-8 py-4">Snapshot</th>
    <th class="bg-green-200 border text-center px-8 py-4">Check tree</th> 
  </tr>
    
  <% @snapshots.each do |snapshot| %>
    <tr>
      <td class="border px-8 py-4"><%= snapshot.id %></td>
      <td class="border px-8 py-4"><%= snapshot.identifier %></td>
      <td class="border px-8 py-4"> 
        <%= link_to snapshot_path(snapshot), class:"text-sm leading-5 text-gray-500 whitespace-no-wrap border-b border-gray-200",
        data: { turbo_method: :get } do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-blue-400 m-auto", fill="none"
          viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 15.75l5.159-5.159a2.25 2.25 0 
            013.182 0l5.159 5.159m-1.5-1.5l1.409-1.409a2.25 2.25 0 013.182 0l2.909 2.909m-18 3.75h16.5a1.5 
            1.5 0 001.5-1.5V6a1.5 1.5 0 00-1.5-1.5H3.75A1.5 1.5 0 002.25 6v12a1.5 1.5 0 001.5 1.5zm10.5-11.25h.008v.008h-.008V8.25zm.375 
            0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
          </svg>
        <% end %>
      </td>
    </tr>      
  <% end %>
</table>

app/views/pools/index.html.erb
<% if current_user.has_role? :manager %>

  <div class="block p-6 rounded-lg shadow-lg bg-white w-1/2 m-auto mb-3">
    <%= form_for Pool.new do |f| %>

      <div class="justify-center mb-6 flex items-center gap-1">
        <%= f.radio_button :type, 'Manager' %>
        <%= f.label :type, 'Manager', value: 'Manager' %>
        <%= f.radio_button :type, 'TeamLead' %>
        <%= f.label :type, 'Team Leader', value: 'TeamLead' %>
        <%= f.radio_button :type, 'Mentor' %>
        <%= f.label :type, 'Mentor', value: 'Mentor' %>
        <%= f.radio_button :type, 'Employee' %>
        <%= f.label :type, 'Employee', value: 'Employee' %>
      </div>

      <div class="text-center mb-6">
        <%= f.label :name, "Parent" %>
        <%= f.select :parent_id, options_for_select(@select_parents) %>
        <%= f.label :name, "Children" %>
        <%= f.select :profile_id, options_for_select(@select_children)%>
      </div>

      <%= button_to "Create New Descent", new_pool_path, method: :get,
      class: 'w-full
          px-6
          py-2.5
          bg-blue-600
          text-white
          font-medium
          text-xs
          leading-tight
          uppercase
          rounded
          shadow-md
          hover:bg-blue-700 hover:shadow-lg
          focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
          active:bg-blue-800 active:shadow-lg
          transition
          duration-150
          ease-in-out' %>
    <% end %>
  </div>
  
  <table class="shadow-lg bg-white border-separate text-center mx-auto">
    <tr>
      <th class="bg-blue-100 border text-center px-6 py-3">ID</th> 
      <th class="bg-blue-100 border text-center px-6 py-3">Parent id</th>
      <th class="bg-blue-100 border text-center px-6 py-3">Type</th>
      <th class="bg-blue-100 border text-center px-6 py-3">User Name</th>
      <th class="bg-blue-100 border text-center px-6 py-3">Grade</th>
      <th class="bg-blue-100 border text-center px-6 py-3">Speciality</th>
      <th class="bg-blue-100 border text-center px-6 py-3 ">Email</th>
      <th class="bg-blue-100 border text-center px-6 py-3">Delete</th>
    </tr>
    <% @pools.decorate.each do |pool| %>
      <tr>
        <td class="border px-6 py-3"><%= pool.id %></td>
        <td class="border px-6 py-3"><%= pool.parent_id %></td>
        <td class="border px-6 py-3"><%= pool.type %></td>
        <td class="border px-6 py-3"><%= pool.full_name %></td>
        <td class="border px-6 py-3"><%= pool.full_grade %></td>
        <td class="border px-6 py-3"><%= pool.profile.speciality.name %></td>
        <td class="border px-6 py-3"><%= pool.profile.user.email %></td>
        <td class="border px-6 py-3"> 
          <%= link_to pool_path(pool), class:"text-sm leading-5 text-gray-500 whitespace-no-wrap border-b border-gray-200",
          data: { turbo_method: :delete, turbo_confirm: 'Delete pool?' } do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-red-400 m-auto", fill="none"
            viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 7.5l-.625 10.632a2.25
            2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5m8.25 3v6.75m0 0l-3-3m3
            3l3-3M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621
            0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" />
            </svg>
          <% end %>
        </td>
      </tr>      
    <% end %>
  </table>
  
  <table class="text-center mx-auto">
    <th><%= paginate @pools %></th> 
  </table>

  <div class="justify-center flex items-center mt-8">
    <% if @pools.present? %>
      <img src='<%=pool_graph_pools_path(r: Time.now.to_i)%>'>
    <% else %>
      <%= 'EMPTY TREE' %>
    <% end %>
  </div>

<% else %>

  <p class="text-2xl text-center mb-5 mt-5">Current User</p>

  <table class="shadow-lg bg-white border-separate text-center mx-auto">
    <tr>
      <th class="bg-blue-100 border text-center px-6 py-3">First Name</th>
      <th class="bg-blue-100 border text-center px-6 py-3">Last Name</th>
      <th class="bg-blue-100 border text-center px-6 py-3">Grade</th>
      <th class="bg-blue-100 border text-center px-6 py-3">Grade level</th>
      <th class="bg-blue-100 border text-center px-6 py-3">Speciality</th>
      <th class="bg-blue-100 border text-center px-6 py-3">Email</th>
    </tr>
    <tr>
      <td class="border px-6 py-3"><%= current_user.profile.first_name %></td>
      <td class="border px-6 py-3"><%= current_user.profile.last_name %></td>
      <td class="border px-6 py-3"><%= current_user.profile.grade.name %></td>
      <td class="border px-6 py-3"><%= current_user.profile.grade.level %></td>
      <td class="border px-6 py-3"><%= current_user.profile.speciality.name %></td>
      <td class="border px-6 py-3"><%= current_user.email %></td>
      </tr>      
  </table>

  <div class="justify-center flex items-center mt-8">
    <% if current_user.profile.pool.present? %>
      <img src='<%=pool_graph_pools_path(r: Time.now.to_i)%>'>
    <% else%>
      <p class="text-2xl text-center mb-5 mt-5">The current user is not in the pool</p>
    <% end %>
  </div>
<% end %>

app/views/snapshots/index.html.erb
<p class="text-2xl text-center mb-5 mt-5">Select the date and click Check tree image</p>

<table class="shadow-lg bg-white border-separate text-left mx-auto">
  <tr>
    <th class="bg-green-200 border text-center px-6 py-3">Id</th> 
    <th class="bg-green-200 border text-center px-6 py-3">Create time</th>
    <th class="bg-green-200 border text-center px-6 py-3">Creator</th>
    <th class="bg-green-200 border text-center px-6 py-3">Check tree</th>
    <th class="bg-green-200 border text-center px-6 py-3">Delete</th> 
  </tr>
    
  <% @snapshots.each do |snapshot| %>
    <tr>
      <td class="border px-6 py-3"><%= snapshot.id %></td>
      <td class="border px-6 py-3"><%= snapshot.identifier %></td>
      <td class="border px-6 py-3"><%= snapshot.user.profile.first_name %></td>
      <td class="border px-6 py-3"> 
        <%= link_to snapshot_path(snapshot), class:"text-sm leading-5 text-gray-500 whitespace-no-wrap border-b border-gray-200",
        data: { turbo_method: :get } do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-blue-400 m-auto", fill="none"
          viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 15.75l5.159-5.159a2.25 2.25 0 
            013.182 0l5.159 5.159m-1.5-1.5l1.409-1.409a2.25 2.25 0 013.182 0l2.909 2.909m-18 3.75h16.5a1.5 
            1.5 0 001.5-1.5V6a1.5 1.5 0 00-1.5-1.5H3.75A1.5 1.5 0 002.25 6v12a1.5 1.5 0 001.5 1.5zm10.5-11.25h.008v.008h-.008V8.25zm.375 
            0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
          </svg>
        <% end %>
      </td>
      <td class="border px-6 py-3"> 
          <%= link_to snapshot_path(snapshot), class:"text-sm leading-5 text-gray-500 whitespace-no-wrap border-b border-gray-200",
          data: { turbo_method: :delete, turbo_confirm: 'Delete snapshot?' } do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-red-400 m-auto", fill="none"
            viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 7.5l-.625 10.632a2.25
            2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5m8.25 3v6.75m0 0l-3-3m3
            3l3-3M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621
            0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" />
            </svg>
          <% end %>
        </td>
    </tr>      
  <% end %>
</table>

<table class="text-center mx-auto">
  <th><%= paginate @snapshots %></th> 
</table>

app/views/snapshots/show.html.erb
<table class="shadow-lg bg-white border-separate text-left mx-auto">
  <tr>
    <th class="bg-green-200 border text-center px-6 py-3">Id</th> 
    <th class="bg-green-200 border text-center px-6 py-3">Create time</th>
    <th class="bg-green-200 border text-center px-6 py-3">Creator</th>
    <th class="bg-green-200 border text-center px-6 py-3">Check tree</th>
    <th class="bg-green-200 border text-center px-6 py-3">Delete</th> 
  </tr>
    
  <% @snapshots.each do |snapshot| %>
    <tr>
      <td class="border px-6 py-3"><%= snapshot.id %></td>
      <td class="border px-6 py-3"><%= snapshot.identifier %></td>
      <td class="border px-6 py-3"><%= snapshot.user.profile.first_name %></td>
      <td class="border px-6 py-3"> 
        <%= link_to snapshot_path(snapshot), class:"text-sm leading-5 text-gray-500 whitespace-no-wrap border-b border-gray-200",
        data: { turbo_method: :get } do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-blue-400 m-auto", fill="none"
          viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 15.75l5.159-5.159a2.25 2.25 0 
            013.182 0l5.159 5.159m-1.5-1.5l1.409-1.409a2.25 2.25 0 013.182 0l2.909 2.909m-18 3.75h16.5a1.5 
            1.5 0 001.5-1.5V6a1.5 1.5 0 00-1.5-1.5H3.75A1.5 1.5 0 002.25 6v12a1.5 1.5 0 001.5 1.5zm10.5-11.25h.008v.008h-.008V8.25zm.375 
            0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
          </svg>
        <% end %>
      </td>
      <td class="border px-6 py-3"> 
          <%= link_to snapshot_path(snapshot), class:"text-sm leading-5 text-gray-500 whitespace-no-wrap border-b border-gray-200",
          data: { turbo_method: :delete, turbo_confirm: 'Delete snapshot?' } do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-red-400 m-auto", fill="none"
            viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 7.5l-.625 10.632a2.25
            2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5m8.25 3v6.75m0 0l-3-3m3
            3l3-3M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621
            0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" />
            </svg>
          <% end %>
        </td>
    </tr>      
  <% end %>
</table>

<table class="text-center mx-auto">
  <th><%= paginate @snapshots %></th> 
</table>

<div class="justify-center flex items-center mt-8 mb-5">
  <img src= '<%=snapshot_snapshot_graph_path(@snapshot)%>'>
</div>